### PR TITLE
Docker-based environment

### PR DESCRIPTION
**Pull request by johnkpark**
First of all, thank you @tovrstra and @jeveki for making this resource publicly available. As a software engineer who's interested in computational chemistry, this has been immensely helpful in getting to know OpenMM.

Here's my little contribution to the project, which is a docker image based running environment. I've added instructions on how to utilize this tool to get started quickly on a laptop, but please feel free to update them as necessary.

Thanks again for the great tutorial!

### CODE REVIEW

**Comment by tovrstra** [comment]
@johnkpark Thank you for this pull request! This would be a very cool addition. I'm not so experienced with Docker, so your contribution is very welcome.

I gave it a quick try with podman, but Jupyter raises an exception because it cannot access the `/tutorial`:

```
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
      File "/opt/conda/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 920, in get
        model = await self._dir_model(path, content=content)
      File "/opt/conda/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 771, in _dir_model
        dir_contents = await run_sync(os.listdir, os_dir)
      File "/opt/conda/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
        return await get_async_backend().run_sync_in_worker_thread(
      File "/opt/conda/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
        return await future
      File "/opt/conda/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 859, in run
        result = context.run(func, *args)
    PermissionError: [Errno 13] Permission denied: '/tutorial'
```

Is this a problem on my end?

**Comment by johnkpark** [comment]
@tovrstra Thanks for the quick response and testing the shell script. I don't think it's your "problem" per se, but there might be some differences in how the UID:GID of the repo's directory is set between our environments.

e.g. if I run `ls -ld $(pwd)` on my m1 Macbook, I get this:

```
drwxr-xr-x@ 28 johnpark  staff  896 Jul 17 20:18 /Users/johnpark/Projects/repos/openmm-tutorial-msbs
```

Things to note here are that the UID:GID of the dir is consistent with `id -u`:`id -g` and that the current user has "write" access to the dir. All this to say that I've added an option in the shell script to preserve the UID:GID from the host machine, so hopefully this will fix the issue on your end without your having to make any changes on your system.

While debugging this, I also uncovered an extra step involved with using Podman in Linux (Ubuntu) system. i.e. docker registry's url needed to be manually specified. I've added the instruction in the `setup_laptop.md` file.

So far I've tested the script on m1 Macbook and Linux Ubuntu 22.04. They both seem to work on my side, but let me know if you're still running into any issues (knowing your environment would be helpful for debugging purposes).

**Comment by tovrstra** [comment]
I still have the problem (on Fedora Linux 40 Worksstation). I should get a better understanding of how podman works. It's probably a minor issue.

**Comment by jeveki** [comment]
For me it works without problems on WSL2 (Ubuntu 22.04). Thanks, @johnkpark, very useful.

**Comment by tovrstra** [comment]
Thanks for testing. We'll merge now and figure out how to solve the podman issue later.

**Pull request merged**
